- name: Web app deployment
  hosts: servers
  become: false
  any_errors_fatal: true
  vars_files:
    - "./vars/vars_app.yml"
  tasks:
    - name: set nameservers
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/resolv.conf"
        line: "nameserver 8.8.8.8"
    - name: Listez le contenu du /home/cloud
      ansible.builtin.command: ls /home/cloud
      register: home_cloud
      changed_when: false
    - name: Install packages
      become: true
      ansible.builtin.apt:
        name: "{{app_packages}}"
        state: present
    - name: Create document root
      become: true
      file:
        path: "{{ app_directory }}"
        owner: "{{ app_user }}"
        state: directory
        mode: '0755'
    - name: Copy index test page
      template:
        src: "templates/index.html.j2"
        dest: "{{ app_directory }}/index.html"
    - name: ensure services started
      ansible.builtin.service:
        name: "{{item}}"
        state: started
      loop: "{{app_packages}}"
    - name: "Allow HTTP on port {{ http_port }}"
      become: true
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        zone: public
      register: fw
    - name: restart firewalld if needed
      become: true
      ansible.builtin.service:
        name: "firewalld"
        state: restarted
      when: fw.changed
    - name: Pause play until a URL is reachable from this host
      delegate_to: localhost
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}:80"
        follow_redirects: none
        method: GET
      register: _result
      until: _result.status == 200
      retries: 10 # 720 * 5 seconds = 1hour (60*60/5)
      delay: 5 # Every 5 seconds